% NGF - Static stability (Tim Attwell, 20.05.19)
% Takes aircraft design properties and finds the static stability and
% static margin of the design.
%% Housekeeping
close all
clear
clc

%% Aircraft geometric properties, values, and constants.
L_f = 20 ;      % Fuselage length(m)
w_f = ??? ;     % Fuselage max width(m)
S_w = 59.65792 ;      % Wing area(m^2)
cbar = ??? ;    % Mean aerodynamic chord(m)
AR = 2.5 ;         % Aspect ratio
LAMBD_14 =  ;  % Sweep at quater chord (deg)
lambda =  ;     % Taper ratio
h_h =  ;        % Height of horizontal stabalizer ABOVE the wing(m)
l_h =  ;        % Length of horizontal stabalizer BEHIND the wing(m)
b =  ;          % Wing span(m)
K_f = 2.8 ;     % Fuselage pitching moment constant found from NACA TR-711
C_m0_w =  ;     % Incompressible airfoil zero lift pitching moment 
eps1 =  ;       % Wing twist (deg)

%% Longitudinal Static Stability

% Pitching moment generated by the fuselage empirically given by:
C_mf = K_f * (L_f) * (w_f^2) / (cbar * S_w) ;

% Tail efficiency accounts for difference between dynamic pressure at the
% tail and that at freestream
eta_h = 0.9 ;   % Tailplane efficency factor
eta_v = 1 ;     % Efficiency of v section of tail is increased

% Downwash effect on the horizontal stabalizer
% alf_h = alf - eps
% dalf_h / dalf = 1 - deps / dalf = depsdalf

% deps / dalf given empirically by:
K_A = (1 / AR) - (1 / (1 + AR^1.7)) ;
K_lambda = (10 - 3 * lambda) / 7 ;
K_h = (1 - abs(h_h/b)) / ((2 * l_h / b)^(1/3)) ;

depsdalf = 4.44 * ((K_A * K_lambda * K_h * ((cosd(LAMBDA_14))^(1/2)))^(1.19)) * (a_w / a_w_0) ;

% Aerodynamic centre estimation
if M >= 1.1
    dx_ac = 0.112 - 0.004 * M ;          % Supersonic x_ac
elseif M < 11 && M > 0.4
    dx_ac = 0.26 * power(M - 0.4, 2.5) ; % Subsonic x_ac
    
x_ac = x_c4 + dx_ac * sqrt(S_w) ;

% Bringing everything together:
dCmcgdalf = -a_w * ((x_ac_w - x_cg)/cbar) + C_Mf ...                                           % Contribution of main wing
    - (eta_h * a_h * (1 - depsdalf) * (S_h / S_w) * ((x_ac_h - x_cg)/cbar)) ...                % Contribution of horizontal section
    - (eta_v * a_v * (1 - depsdalf) * (S_v / S_w) * ((x_ac_h - x_cg)/cbar) * sind(thetaV)) ;   % Contribution of 'V' section

if dCmcfdalf > 0
    disp("The aircraft is unstable in pitch (dC_m/d_alf > 0)")
elseif dCmcfdalpf == 0
    disp("The aircraft is neutrally stable in pitch(dC_m/d_alf = 0)")
elseif dCmcfdalpf < 0
    disp("The aircraft is stable in pitch(dC_m/d_alf < 0)")
end

%% Neutral point and static margin

% Neutral point calculation
x_np = cbar * ((a_w * (x_ac_w / cbar)) - C_Mf ... 
    + (eta_h * a_h * (1 - depsdalf) * (S_h / S_w) * (x_ac_h / cbar)) ...
    + (eta_v * a_v * (1 - depsdalf) * (S_v / S_w) * (x_ac_v / cbar) * sind(thetaV)) ...
    / (a_w ...
    + (eta_h * a_h * (1 - depsdalf) * (S_h / S_w)) ...
    + (eta_v * a_v * (1 - depsdalf) * (S_v / S_w) * sind(thetaV)))) ;

% Engine off static margin 
SMoff = (x_np - x_cg) / cbar

if SMoff > 20
    disp("The static margin is way too high! (SM>20)")
elseif SMoff <= 20 && SMoff > 7
    disp("The static margin is high, even for a transport! (7<SM<20")
elseif SMoff <= 7 && SMoff > 4
    disp("The static margin is that of a transport! (4<SM<7)")
elseif SMoff <= 4 && SMoff > 2
    disp("The static margin is that of an early fighter! (0<SM<4)")
elseif SMoff <= 0 && SMoff > -15
    disp("The static margin is that of a modern fighter! (-15<SM<0)")
elseif SMoff <= -15
    disp("The static margin is way too low! (SM<-15)")
end

% Rough engine-on calculation based on past experience
SMon = SMoff - 0.02 

%% Trim Analysis

% Wing zero lif pirching moment empirical calculation:
C_M0_w = (C_m0_airf_0 * ((A * cosd(LAMBDA_14) * cosd(LAMBDA_14)) / (A + 2 * cosd(LAMBDA_14))) - 0.01 * eps1) * (a_w / a_w_0) ;

% Thrust effects:
% In steady level flight:
T = q * S_w * C_D ;
Z_t =  ;           % Distance between vertical cg and thrustline (+ve if thrustline under cg)

% Lift of lifting surfaces:
C_L_w = a_w * (alf + i_w - alf_0_w) ;
C_L_h = a_h * ((alf + i_w - alf_0_w) * (1 - depsdalf) + (i_h - i_w) - (alf_0_h - alf_0_w))


% Total lift and pitching moments about cg for a clean a/c
C_M_cg = (-C_L_w * (x_ac_w - x_cg) / cbar) + C_M0_w + (C_Mf * alf) - (eta_h * C_l_h * (S_h / S_w) * ((x_ac_h - x_cg) / cbar) + ((Z_t * T) / (q * S_w * cbar)) ;
C_L = C_L_w + (eta_h * (S_h / S_w) * C_L_h ;

% Design point
C_L_des = W_des / (q_des * S_w) ; 
C_M_cg_des = 0 ;

i_h = [-3:2:15] ; 

figure(1)
hold on; grid on
for ii = 0 : 9
    plot(CL(ii), C_M_cd(ii)


end

%% Lateral stability


C_n_beta_w = C_L^2 * ((1 / (4 * pi * AR)) - ...
    (tand(LAMBDA_14) / (pi * AR * (AR + 4 * cosd(LAMBDA_14)))) * ...
    (cosd(LAMBDA_14) - (AR / 2) - (AR^2 / (8 * cosd(LAMBDA_14))) + ...
    (6 * (x_ac_w - x_cg) * sind(LAMBDA_14) / (AR * cbar)))) ;


C_n_beta_fus = -1.3 * volume * (D_f / W_f) / (S_w * b) ;

BvBetav = 0.724 + ((3.06 * (S_vs / S_w)) / (1 + cosd(LAMBDA_14))) - ...
    0.4 * (Z_wf / D_f) + (0.009 * AR) ; 

C_n_beta_v = C_F_beta_v * BvBetav * (S_v / S_w) * (x_ac_v - x_cg) / cbar ;


ClbetawCL =  ;

C_l_beta_gam = (-a * gam / 4) * ((2 * (1 + 2*lambda)) / (3 * (1 + lambda))) ;

C_beta_wf = -1.2 * ((sqrt(AR) * Z_wf * (D_f + W_f)) / (b^2)) ;

C_l_beta_w = ClbetawCL * C_L + C_l_beta_gam + C_l_beta_wf ;

C_l_beta_v = -C_F_beta_v * BvBetav * (S_v / S_w) * Z_v / cbar ;


C_n_beta = C_n_beta_w + C_n_beta_fus + C_n_beta_v ;

C_l_beta = C_l_beta_w + C_l_beta_v ;


















